<a href="https://colab.research.google.com/github/spshreya/datamining/blob/master/DA_Assignment_shreyaPandey.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
uploaded = files.upload()

Saving VIJP_hourly.csv to VIJP_hourly.csv
Saving VIDP_hourly.csv to VIDP_hourly.csv
Saving VAUD_hourly.csv to VAUD_hourly.csv


In [29]:
import pandas as pd

In [30]:
df1 = pd.read_csv('VIJP_hourly.csv')
df2 = pd.read_csv('VIDP_hourly.csv')
df3 = pd.read_csv('VAUD_hourly.csv')

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (3,16) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [31]:
df1.head()

State Code   ...  Solar radiation [optional] (Integer - minutes)
0        VIJP  ...                                               *
1        VIJP  ...                                               *
2        VIJP  ...                                               *
3        VIJP  ...                                               *
4        VIJP  ...                                               *

[5 rows x 32 columns]

In [32]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87740 entries, 0 to 87739
Data columns (total 32 columns):
 #   Column                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             Non-Null Count  Dtype  
---  ------                                                                                                                                                                                                                                                

In [33]:
df2.rename(columns={"State Location":"State Code "}, inplace= True)
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91161 entries, 0 to 91160
Data columns (total 32 columns):
 #   Column                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             Non-Null Count  Dtype  
---  ------                                                                                                                                                                                                                                                

In [34]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41619 entries, 0 to 41618
Data columns (total 32 columns):
 #   Column                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             Non-Null Count  Dtype  
---  ------                                                                                                                                                                                                                                                

In [35]:
dfs = [df1, df2, df3]
df = pd.concat(dfs)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 220520 entries, 0 to 41618
Data columns (total 32 columns):
 #   Column                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             Non-Null Count   Dtype  
---  ------                                                                                                                                                                                                                                              

In [36]:
pd.unique(df['State Code '])

array(['VIJP', 'VIDP', 'VAUD'], dtype=object)

In [37]:
import numpy as np
df.replace(to_replace = "*", value = np.nan, inplace=True)   

In [38]:
df.describe()

observation time in local time (String as YYYYMMDDhhmm)  ...  Solar radiation [optional] (Integer - minutes)
count                                       2.205200e+05        ...                                             0.0
mean                                        2.018868e+11        ...                                             NaN
std                                         1.338637e+08        ...                                             NaN
min                                         2.016120e+11        ...                                             NaN
25%                                         2.018020e+11        ...                                             NaN
50%                                         2.019040e+11        ...                                             NaN
75%                                         2.020060e+11        ...                                             NaN
max                                         2.021080e+11        ...                                             NaN

[8 rows x 8 columns]

In [39]:
pd.unique(df['precipitation descriptor (Integer - see lookup)'])

array([nan, '20', '7', '1', '19', '23', '9', '8', '21', '12', '24'],
      dtype=object)

In [40]:
df['precipitation descriptor (Integer - see lookup)'] = df['precipitation descriptor (Integer - see lookup)'].astype(float)
df['precipitation descriptor (Integer - see lookup)'].fillna((df['precipitation descriptor (Integer - see lookup)'].mean()),inplace=True)
pd.unique(df['precipitation descriptor (Integer - see lookup)'])

array([11.06542645, 20.        ,  7.        ,  1.        , 19.        ,
       23.        ,  9.        ,  8.        , 21.        , 12.        ,
       24.        ])

In [41]:
pd.unique(df['temperature descriptor (Integer - see lookup)'])

array(['6', '8', '9', '7', '5', '4', nan, '10', '11', '12'], dtype=object)

In [43]:
df['temperature descriptor (Integer - see lookup)'] = df['temperature descriptor (Integer - see lookup)'].astype(float)
df['temperature descriptor (Integer - see lookup)'].fillna((df['temperature descriptor (Integer - see lookup)'].mean()),inplace=True)
pd.unique(df['temperature descriptor (Integer - see lookup)'])

array([ 6.       ,  8.       ,  9.       ,  7.       ,  5.       ,
        4.       ,  9.3008374, 10.       , 11.       , 12.       ])

In [46]:
pd.unique(df['temperature descriptor (Integer - see lookup)'])

array([ 6.       ,  8.       ,  9.       ,  7.       ,  5.       ,
        4.       ,  9.3008374, 10.       , 11.       , 12.       ])

In [45]:
nan_values = df.isna()
nan_columns = nan_values.any()

columns_with_nan = df.columns[nan_columns].tolist()
print(columns_with_nan)

['sky descriptor (Integer - see lookup)', 'additional air descriptor (optional) (Integer - see lookup)', 'temperature (Floating Point - Celsius)', 'wind speed (Floating Point - knots.)', 'wind gusts [optional] (Floating  Point - knots.)', 'humidity (Integer - percent)', 'dew point (Floating Point - Celsius)', 'comfort level (Floating Point - Celsius)', 'sea level pressure (Floating Point - millibars)', "barometric tendency ('S' - Steady; 'F' - Falling; 'R' - Rising)", 'visibility (Floating Point - miles)', 'sky conditions (C-lear;F-ew;S-cattered;B-roken;O-vercast; X-obscured)', 'minimum cloud base (Floating Point - meters)', 'maximum cloud base (Floating Point - meters)', "weather type (+FC = tornado/waterspout; FC = funnel cloud; TS = thunderstorm; GR = hail; RA = rain; DZ = drizzle; SN = snow; SG = snow grains; GS = small hail &/or snow pellets; PE = ice pellets; IC = crystals; FG+ = heavy fog less than 0.25 miles vis; FG = fog; BR = mist; UP = unknown precip.; HZ = haze; FU = smoke;

In [47]:
pd.unique(df['temperature (Floating Point - Celsius)'])

array(['14.8', '15', '14.6', '14', '13.4', '13', '13.7', '16', '17', '18',
       '19', '20', '20.6', '21', '22', '23', '24', '21.6', '15.6', '12.6',
       '12', '11', '11.4', '19.6', '21.8', '16.8', '14.2', '11.6', '12.4',
       '22.4', '16.6', '13.6', '10', '18.6', '14.4', '10.8', '25', '23.6',
       '19.8', '22.2', '19.2', '18.4', '15.2', '18.8', '21.4', '17.6',
       '10.6', '11.8', '17.2', '20.4', '9', '9.2', '8', '17.8', '13.8',
       '11.2', '7.2', '7', '6', '5.6', '5', '15.4', '16.2', '4', '4.2',
       '7.6', '16.4', '12.2', '9.4', '7.8', '8.6', '15.8', nan, '13.2',
       '18.2', '6.8', '10.4', '20.7', '19.4', '8.8', '22.8', '20.8',
       '8.2', '20.2', '23.8', '25.8', '24.4', '26', '27', '26.8', '28',
       '11.1', '22.6', '23.2', '17.4', '25.6', '21.2', '23.4', '25.2',
       '25.4', '24.6', '10.2', '12.8', '26.6', '28.8', '27.2', '29', '30',
       '28.6', '28.4', '31', '29.6', '27.4', '32', '30.8', '27.8', '33',
       '32.6', '29.8', '24.8', '26.4', '26.2', '29.4'

In [48]:
pd.unique(df['wind speed (Floating Point - knots.)'])

array(['7.56', '5.4', '1.8', '3.6', '9.36', '0', '12.96', '11.16',
       '14.76', '16.56', '18.36', '20.52', nan, '22.32', '24.12', '27.72',
       '33.48', '35.28', '25.92', '38.88', '29.52', '18', '31.68',
       '46.44', '37.08', '50.04', '14.4', '88.92', '10.8', '28.8', '21.6',
       '85.32', '7.2', '40.68', '92.52', '9.27', '48.24', '55.44', '59.4',
       '44.64', '42.48', '32.4', '74.16', '77.76', '66.6', '39.6'],
      dtype=object)

In [51]:
df['temperature (Floating Point - Celsius)'] = df['temperature (Floating Point - Celsius)'].astype(float)
df['temperature (Floating Point - Celsius)'].fillna((df['temperature (Floating Point - Celsius)'].mean()),inplace=True)
pd.unique(df['temperature (Floating Point - Celsius)'])

array([14.8       , 15.        , 14.6       , 14.        , 13.4       ,
       13.        , 13.7       , 16.        , 17.        , 18.        ,
       19.        , 20.        , 20.6       , 21.        , 22.        ,
       23.        , 24.        , 21.6       , 15.6       , 12.6       ,
       12.        , 11.        , 11.4       , 19.6       , 21.8       ,
       16.8       , 14.2       , 11.6       , 12.4       , 22.4       ,
       16.6       , 13.6       , 10.        , 18.6       , 14.4       ,
       10.8       , 25.        , 23.6       , 19.8       , 22.2       ,
       19.2       , 18.4       , 15.2       , 18.8       , 21.4       ,
       17.6       , 10.6       , 11.8       , 17.2       , 20.4       ,
        9.        ,  9.2       ,  8.        , 17.8       , 13.8       ,
       11.2       ,  7.2       ,  7.        ,  6.        ,  5.6       ,
        5.        , 15.4       , 16.2       ,  4.        ,  4.2       ,
        7.6       , 16.4       , 12.2       ,  9.4       ,  7.8 

In [53]:
df['wind speed (Floating Point - knots.)'] = df['wind speed (Floating Point - knots.)'].astype(float)
df['wind speed (Floating Point - knots.)'].fillna((df['wind speed (Floating Point - knots.)'].mean()),inplace=True)
pd.unique(df['wind speed (Floating Point - knots.)'])

array([ 7.56      ,  5.4       ,  1.8       ,  3.6       ,  9.36      ,
        0.        , 12.96      , 11.16      , 14.76      , 16.56      ,
       18.36      , 20.52      ,  7.76640468, 22.32      , 24.12      ,
       27.72      , 33.48      , 35.28      , 25.92      , 38.88      ,
       29.52      , 18.        , 31.68      , 46.44      , 37.08      ,
       50.04      , 14.4       , 88.92      , 10.8       , 28.8       ,
       21.6       , 85.32      ,  7.2       , 40.68      , 92.52      ,
        9.27      , 48.24      , 55.44      , 59.4       , 44.64      ,
       42.48      , 32.4       , 74.16      , 77.76      , 66.6       ,
       39.6       ])